import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StudentBadge from "@/components/StudentBadge";
import Header  from "@/components/header";
import Footer from "@/components/footer";
import { ThemeProvider } from "next-themes";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <a
      href="#main"
      className="sr-only focus:not-sr-only focus:absolute top-2 left-2 
            bg-white text-black dark:bg-black dark:text-white p-2 rounded"
            >
              Skip to content
    </a>
        <StudentBadge />
        <Header />
        <main id="main" className="max-w-3xl mx-auto px-4 py-6">
        {children}
        </main>
        <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
